/* This file was generated by SableCC (http://www.sablecc.org/). */

package srt.sableccCarpeta.analysis;

import srt.sableccCarpeta.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseASubtituloListasubtitulo(ASubtituloListasubtitulo node);
    void caseAListsubtituloListasubtitulo(AListsubtituloListasubtitulo node);
    void caseASubtitulo(ASubtitulo node);
    void caseATiempo(ATiempo node);
    void caseAHora1(AHora1 node);
    void caseAHora2(AHora2 node);
    void caseAHora(AHora node);
    void caseAMinutos(AMinutos node);
    void caseASegundos(ASegundos node);
    void caseAMiliseg(AMiliseg node);
    void caseASubTextlist(ASubTextlist node);
    void caseATextlistTextlist(ATextlistTextlist node);
    void caseASub1Sub(ASub1Sub node);
    void caseASub2Sub(ASub2Sub node);

    void caseTDigito(TDigito node);
    void caseTBlank(TBlank node);
    void caseTTexto(TTexto node);
    void caseTComa(TComa node);
    void caseTDosp(TDosp node);
    void caseTFlecha(TFlecha node);
    void caseTEtiqueta(TEtiqueta node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
