/* This file was generated by SableCC (http://www.sablecc.org/). */

package srt.sableccCarpeta.node;

import srt.sableccCarpeta.analysis.*;

@SuppressWarnings("nls")
public final class AHora extends PHora
{
    private TDigito _digito_;

    public AHora()
    {
        // Constructor
    }

    public AHora(
        @SuppressWarnings("hiding") TDigito _digito_)
    {
        // Constructor
        setDigito(_digito_);

    }

    @Override
    public Object clone()
    {
        return new AHora(
            cloneNode(this._digito_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHora(this);
    }

    public TDigito getDigito()
    {
        return this._digito_;
    }

    public void setDigito(TDigito node)
    {
        if(this._digito_ != null)
        {
            this._digito_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._digito_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._digito_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._digito_ == child)
        {
            this._digito_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._digito_ == oldChild)
        {
            setDigito((TDigito) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
