/* This file was generated by SableCC (http://www.sablecc.org/). */

package srt.sableccCarpeta.node;

import srt.sableccCarpeta.analysis.*;

@SuppressWarnings("nls")
public final class ASub2Sub extends PSub
{
    private TTexto _texto_;

    public ASub2Sub()
    {
        // Constructor
    }

    public ASub2Sub(
        @SuppressWarnings("hiding") TTexto _texto_)
    {
        // Constructor
        setTexto(_texto_);

    }

    @Override
    public Object clone()
    {
        return new ASub2Sub(
            cloneNode(this._texto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASub2Sub(this);
    }

    public TTexto getTexto()
    {
        return this._texto_;
    }

    public void setTexto(TTexto node)
    {
        if(this._texto_ != null)
        {
            this._texto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._texto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._texto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._texto_ == child)
        {
            this._texto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._texto_ == oldChild)
        {
            setTexto((TTexto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
