/* This file was generated by SableCC (http://www.sablecc.org/). */

package srt.sableccCarpeta.node;

import srt.sableccCarpeta.analysis.*;

@SuppressWarnings("nls")
public final class ASubtitulo extends PSubtitulo
{
    private TDigito _digito_;
    private PTiempo _tiempo_;
    private PTextlist _textlist_;

    public ASubtitulo()
    {
        // Constructor
    }

    public ASubtitulo(
        @SuppressWarnings("hiding") TDigito _digito_,
        @SuppressWarnings("hiding") PTiempo _tiempo_,
        @SuppressWarnings("hiding") PTextlist _textlist_)
    {
        // Constructor
        setDigito(_digito_);

        setTiempo(_tiempo_);

        setTextlist(_textlist_);

    }

    @Override
    public Object clone()
    {
        return new ASubtitulo(
            cloneNode(this._digito_),
            cloneNode(this._tiempo_),
            cloneNode(this._textlist_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubtitulo(this);
    }

    public TDigito getDigito()
    {
        return this._digito_;
    }

    public void setDigito(TDigito node)
    {
        if(this._digito_ != null)
        {
            this._digito_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._digito_ = node;
    }

    public PTiempo getTiempo()
    {
        return this._tiempo_;
    }

    public void setTiempo(PTiempo node)
    {
        if(this._tiempo_ != null)
        {
            this._tiempo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tiempo_ = node;
    }

    public PTextlist getTextlist()
    {
        return this._textlist_;
    }

    public void setTextlist(PTextlist node)
    {
        if(this._textlist_ != null)
        {
            this._textlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._textlist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._digito_)
            + toString(this._tiempo_)
            + toString(this._textlist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._digito_ == child)
        {
            this._digito_ = null;
            return;
        }

        if(this._tiempo_ == child)
        {
            this._tiempo_ = null;
            return;
        }

        if(this._textlist_ == child)
        {
            this._textlist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._digito_ == oldChild)
        {
            setDigito((TDigito) newChild);
            return;
        }

        if(this._tiempo_ == oldChild)
        {
            setTiempo((PTiempo) newChild);
            return;
        }

        if(this._textlist_ == oldChild)
        {
            setTextlist((PTextlist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
