/* This file was generated by SableCC (http://www.sablecc.org/). */

package srt.sableccCarpeta.node;

import srt.sableccCarpeta.analysis.*;

@SuppressWarnings("nls")
public final class ASubtituloListasubtitulo extends PListasubtitulo
{
    private PSubtitulo _subtitulo_;

    public ASubtituloListasubtitulo()
    {
        // Constructor
    }

    public ASubtituloListasubtitulo(
        @SuppressWarnings("hiding") PSubtitulo _subtitulo_)
    {
        // Constructor
        setSubtitulo(_subtitulo_);

    }

    @Override
    public Object clone()
    {
        return new ASubtituloListasubtitulo(
            cloneNode(this._subtitulo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubtituloListasubtitulo(this);
    }

    public PSubtitulo getSubtitulo()
    {
        return this._subtitulo_;
    }

    public void setSubtitulo(PSubtitulo node)
    {
        if(this._subtitulo_ != null)
        {
            this._subtitulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subtitulo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subtitulo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subtitulo_ == child)
        {
            this._subtitulo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subtitulo_ == oldChild)
        {
            setSubtitulo((PSubtitulo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
