/* This file was generated by SableCC (http://www.sablecc.org/). */

package srt.sableccCarpeta.node;

import srt.sableccCarpeta.analysis.*;

@SuppressWarnings("nls")
public final class ATextlistTextlist extends PTextlist
{
    private PSub _sub_;
    private PTextlist _textlist_;

    public ATextlistTextlist()
    {
        // Constructor
    }

    public ATextlistTextlist(
        @SuppressWarnings("hiding") PSub _sub_,
        @SuppressWarnings("hiding") PTextlist _textlist_)
    {
        // Constructor
        setSub(_sub_);

        setTextlist(_textlist_);

    }

    @Override
    public Object clone()
    {
        return new ATextlistTextlist(
            cloneNode(this._sub_),
            cloneNode(this._textlist_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATextlistTextlist(this);
    }

    public PSub getSub()
    {
        return this._sub_;
    }

    public void setSub(PSub node)
    {
        if(this._sub_ != null)
        {
            this._sub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sub_ = node;
    }

    public PTextlist getTextlist()
    {
        return this._textlist_;
    }

    public void setTextlist(PTextlist node)
    {
        if(this._textlist_ != null)
        {
            this._textlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._textlist_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sub_)
            + toString(this._textlist_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sub_ == child)
        {
            this._sub_ = null;
            return;
        }

        if(this._textlist_ == child)
        {
            this._textlist_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sub_ == oldChild)
        {
            setSub((PSub) newChild);
            return;
        }

        if(this._textlist_ == oldChild)
        {
            setTextlist((PTextlist) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
