/* This file was generated by SableCC (http://www.sablecc.org/). */

package srt.sableccCarpeta.parser;

import srt.sableccCarpeta.node.*;
import srt.sableccCarpeta.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTDigito(@SuppressWarnings("unused") TDigito node)
    {
        this.index = 0;
    }

    @Override
    public void caseTTexto(@SuppressWarnings("unused") TTexto node)
    {
        this.index = 1;
    }

    @Override
    public void caseTComa(@SuppressWarnings("unused") TComa node)
    {
        this.index = 2;
    }

    @Override
    public void caseTDosp(@SuppressWarnings("unused") TDosp node)
    {
        this.index = 3;
    }

    @Override
    public void caseTFlecha(@SuppressWarnings("unused") TFlecha node)
    {
        this.index = 4;
    }

    @Override
    public void caseTEtiqueta(@SuppressWarnings("unused") TEtiqueta node)
    {
        this.index = 5;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 6;
    }
}
